---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R media $DEPLOYPATH
    - /bin/cp -R Projects $DEPLOYPATH